const WOLF_PACK_NOTE = "En jeu, /lg me affiche aussi la liste des autres membres de la meute que vous connaissez.";

module.exports = [
    {
        command: "villageois",
        name: "Villageois",
        team: "VILLAGE",
        lines: [
            "Aucun pouvoir spécial ne vous est attribué.",
            "Votre seule arme est la survie : repérez les Loups-Garous et affrontez-les directement.",
        ],
    },
    {
        command: "voyante",
        name: "Voyante",
        team: "VILLAGE",
        lines: [
            "/lg sonder <joueur> dévoile le rôle d'un joueur, de jour comme de nuit.",
            "Ce pouvoir se recharge une fois par cycle jour/nuit.",
        ],
    },
    {
        command: "salvateur",
        name: "Salvateur",
        team: "VILLAGE",
        lines: [
            "Le Village est votre camp, et sa victoire scelle la vôtre.",
            "/lg proteger <joueur> place un joueur sous protection jusqu'à la fin de l'épisode en cours, une fois par épisode.",
            "La cible bénéficie de Résistance I et d'une réduction de 50% des dégâts de chute, sans jamais en être avertie.",
        ],
    },
    {
        command: "idiot_du_village",
        name: "Idiot du Village",
        team: "VILLAGE",
        lines: [
            "Votre camp est le Village, et sa victoire est la vôtre.",
            "Tant que celui qui vous porte le coup fatal n'appartient pas au camp des Loups, vous survivez automatiquement (une fois par partie) avec 8 cœurs de vie restants, et votre identité d'Idiot du Village est alors révélée à tous.",
            "Un Loup-Garou ou un Père des Loups, en revanche, vous tue sans recours.",
        ],
    },
    {
        command: "ancien",
        name: "Ancien",
        team: "VILLAGE",
        lines: [
            "Votre sort est lié à celui du Village.",
            "Une Résistance 0.5 permanente réduit de 10% tous les dégâts que vous subissez.",
            "Un Loup-Garou ou un Père des Loups qui vous achève vous voit ressusciter (une fois par partie) avec votre vie du moment — mais votre Résistance 0.5 disparaît alors pour de bon.",
            "Un villageois (hors Loups et solitaires) qui vous tue vous laisse mourir normalement, mais perd pour toujours la moitié de sa vie maximale en retour.",
            "Contre un solitaire, votre mort se déroule sans aucun effet secondaire.",
        ],
    },
    {
        command: "bienfaiteur",
        name: "Bienfaiteur",
        team: "VILLAGE",
        lines: [
            "Votre victoire passe par celle du Village.",
            "Deux livres enchantés Protection II vous sont remis en dotation.",
            "/lg conferer <joueur> offre discrètement 1 cœur de vie permanent à un joueur (jamais à vous-même), utilisable sur 3 joueurs distincts, au rythme d'une fois toutes les 5 minutes.",
            "Le bénéficiaire reçoit le don 3 minutes plus tard, sans en avoir été averti.",
            "Vos 3 dons épuisés, vous obtenez à votre tour une régénération continue d'1 cœur par minute.",
        ],
    },
    {
        command: "sorciere",
        name: "Sorcière",
        team: "VILLAGE",
        lines: [
            "Potion de vie : la mort imminente d'un joueur non infecté vous envoie un message cliquable (valable 10s) permettant de le sauver via /lg soigner <joueur> (une fois par partie).",
            "Potion de mort : /lg empoisonner <joueur> retire 2 cœurs de vie maximum à une cible, de façon irréversible (une fois par partie).",
        ],
    },
    {
        command: "chasseur",
        name: "Chasseur",
        team: "VILLAGE",
        lines: [
            "Un arc enchanté Puissance IV, accompagné de flèches, vous est fourni.",
            "Contre le camp des Loups, vos coups portent un bonus de dégâts (Force 0.5 de base), qui progresse de 0.1 à chaque Loup abattu, jusqu'à un plafond de Force I.",
            "Un coup normalement fatal vous laisse 15 secondes de sursis avant la mort définitive.",
            "Durant ce sursis, /lg tirer <joueur> permet une dernière riposte sur une cible différente de votre tueur (une seule fois par partie) :",
            "- Contre un Loup-Garou/Père des Loups : sa vie maximale chute de moitié, de façon irréversible.",
            "- Contre un solitaire : sa vie maximale diminue d'un quart, de façon irréversible.",
            "- Contre un villageois : il perd 6 cœurs de vie actuelle (récupérables).",
            "Vous éliminer ne procure à un Loup-Garou ou un Père des Loups aucun de leurs bonus habituels de Speed/Absorption.",
        ],
    },
    {
        command: "cupidon",
        name: "Cupidon",
        team: "VILLAGE",
        lines: [
            "Votre équipement de départ comprend un arc, des flèches et un livre enchanté Puissance III + Punch I, à assembler sur une enclume.",
            "/lg lier <joueur1> <joueur2> unit deux joueurs par les liens de l'amour, une seule fois par partie.",
            "La mort de l'un entraîne immédiatement celle de l'autre, de chagrin.",
            "Quel que soit leur camp d'origine, un camp Amoureux distinct se forme avec vous dès ce moment, et l'emporte en restant le dernier camp en lice.",
        ],
    },
    {
        command: "petite_fille",
        name: "Petite Fille",
        team: "VILLAGE",
        lines: [
            "Vous délester entièrement de votre armure durant la nuit déclenche une invisibilité de 5 minutes.",
            "Renfiler ne serait-ce qu'une pièce d'armure met fin à l'effet sur-le-champ.",
            "Une seule activation possible par nuit.",
        ],
    },
    {
        command: "loup_garou",
        name: "Loup-Garou",
        team: "LOUP",
        lines: [
            "La nuit venue, vous bénéficiez de Force I.",
            "Aucune procédure de vote ou de ciblage : vous éliminez le Village directement au corps-à-corps, en PVP libre.",
            "Rester proche d'un joueur le corrompt progressivement : +1% toutes les 5 secondes.",
            "Quand une victime corrompue à 100% meurt sous les coups d'un Loup, le Père des Loups a la possibilité de la convertir plutôt que de la laisser mourir.",
            WOLF_PACK_NOTE,
        ],
    },
    {
        command: "pere_des_loups",
        name: "Père des Loups",
        team: "LOUP",
        lines: [
            "Comme un Loup-Garou, vous bénéficiez de Force I chaque nuit.",
            "Votre proximité corrompt les joueurs à un rythme bien plus élevé qu'un Loup-Garou ordinaire : +1% chaque seconde.",
            "Lorsqu'une victime corrompue à 100% succombe sous les coups d'un Loup, un message cliquable vous est envoyé, valable 10 secondes :",
            "/lg infecter <joueur> la convertit en Loup-Garou, /lg laissermourir <joueur> la laisse mourir.",
            WOLF_PACK_NOTE,
        ],
    },
    {
        command: "grand_mechant_loup",
        name: "Grand Méchant Loup",
        team: "LOUP",
        lines: [
            "Contrairement aux autres Loups, votre Force I reste active à toute heure, jour comme nuit.",
            "Aucune procédure de vote ou de ciblage : vous éliminez le Village directement au corps-à-corps, en PVP libre.",
            "Rester proche d'un joueur le corrompt progressivement : +1% toutes les 5 secondes.",
            "Quand une victime corrompue à 100% meurt sous les coups d'un Loup, le Père des Loups a la possibilité de la convertir plutôt que de la laisser mourir.",
            WOLF_PACK_NOTE,
        ],
    },
    {
        command: "loup_garou_craintif",
        name: "Loup-Garou Craintif",
        team: "LOUP",
        lines: [
            "Aucune procédure de vote ou de ciblage : vous éliminez le Village directement au corps-à-corps, en PVP libre.",
            "Rester proche d'un joueur le corrompt progressivement : +1% toutes les 5 secondes.",
            "Votre état varie selon le nombre de Loups-Garous présents dans un rayon de 20 blocs autour de vous (vous y compris) :",
            "- Au-delà de 4 loups à portée : Faiblesse I.",
            "- 2 loups ou moins à portée : Résistance I de jour, Force I de nuit.",
            "- Si vous êtes l'unique loup présent : Speed 0.5 s'ajoute à l'effet ci-dessus.",
            "Votre vote est toujours neutralisé en blanc, et votre mort reste silencieuse : ni la Sorcière ni le Père des Loups ne peuvent intervenir sur votre sort.",
            WOLF_PACK_NOTE,
        ],
    },
    {
        command: "loup_garou_perfide",
        name: "Loup-Garou Perfide",
        team: "LOUP",
        lines: [
            "Comme tout Loup, vous bénéficiez de Force I chaque nuit.",
            "Aucune procédure de vote ou de ciblage : vous éliminez le Village directement au corps-à-corps, en PVP libre.",
            "Rester proche d'un joueur le corrompt progressivement : +1% toutes les 5 secondes.",
            "En vous délestant complètement de votre armure la nuit, vous devenez invisible pour 5 minutes (une activation par nuit).",
            "Le fait de renfiler ne serait-ce qu'une pièce d'armure met fin à l'invisibilité jusqu'au matin.",
            "Tant que vous êtes invisible, la Petite Fille et le Feu Follet peuvent repérer votre position via des particules, et vous repérez les leurs de la même façon.",
            WOLF_PACK_NOTE,
        ],
    },
    {
        command: "vilain_petit_loup",
        name: "Vilain Petit Loup",
        team: "LOUP",
        lines: [
            "En permanence, jour et nuit, vos attaques au corps-à-corps bénéficient d'un bonus de dégâts équivalent à Force 0.5 (+1.5 dégâts).",
            "Un bonus de vitesse supplémentaire (Speed 0.5) s'ajoute à cela durant la nuit.",
            "Aucune procédure de vote ou de ciblage : vous éliminez le Village directement au corps-à-corps, en PVP libre.",
            "Rester proche d'un joueur le corrompt progressivement : +1% toutes les 5 secondes.",
            "Quand une victime corrompue à 100% meurt sous les coups d'un Loup, le Père des Loups a la possibilité de la convertir plutôt que de la laisser mourir.",
            WOLF_PACK_NOTE,
        ],
    },
    {
        command: "chasseur_de_primes",
        name: "Chasseur de Primes",
        team: "NEUTRAL",
        lines: [
            "Rôle solitaire : la victoire exige d'être le dernier en vie, tous les autres camps et solitaires éliminés.",
            "Un premier contrat secret vous est confié dès l'activation du PVP ; le suivant tombe à l'épisode qui suit la réussite du précédent.",
            "Abattre la cible actuellement visée valide le contrat et vous octroie du matériel.",
            "Votre cible en cours (ou l'absence de contrat) vous est indiquée en jeu via /lg me.",
        ],
    },
    {
        command: "loup_blanc",
        name: "Loup Blanc",
        team: "NEUTRAL",
        lines: [
            "Rôle solitaire : la victoire n'est acquise qu'en étant l'ultime survivant, Loups compris.",
            "À la manière d'un Loup, vous obtenez Force I chaque nuit.",
            "La révélation des rôles vous porte à 15 cœurs de vie.",
            "L'identité des Loups-Garous vous est connue, mais gagner exige de tous les éliminer, eux inclus.",
            "La liste des Loups-Garous identifiés vous est affichée en jeu via /lg me.",
        ],
    },
    {
        command: "ange",
        name: "Ange",
        team: "NEUTRAL",
        lines: [
            "L'Ange est un rôle solitaire qui peut prendre deux formes distinctes, à choisir une fois les rôles révélés via /lg ange dechu ou /lg ange gardien :",
            "- Ange Déchu : débute à 12 cœurs, passe à 15 en provoquant (ou en contribuant à) la mort de sa cible assignée. Victoire en solitaire.",
            "- Ange Gardien : débute à 15 cœurs, sa priorité est la victoire de son protégé assigné (rejoint son camp). La mort de ce dernier le fait retomber à 12 cœurs avec une Faiblesse permanente, et il doit alors gagner seul.",
            "En forme Gardienne, dès que le protégé descend sous 4 cœurs, /lg regen lui accorde Régénération I pendant 1 minute (une seule fois par partie).",
            "Votre cible/protégé exact(e) et votre état actuel sont affichés en jeu via /lg me.",
        ],
    },
    {
        command: "feu_follet",
        name: "Feu Follet",
        team: "NEUTRAL",
        lines: [
            "Vous ne pouvez l'emporter que seul, sans allié.",
            "Se dépouiller entièrement de son armure, à n'importe quel moment, déclenche une invisibilité sans limite de durée (stoppée dès qu'une pièce d'armure est remise).",
            "Une fois invisible, des particules trahissent votre position aux yeux de la Petite Fille et du Loup-Garou Perfide — et réciproquement, vous percevez les leurs.",
            "/lg folie déclenche votre Folie Incendiaire (rechargement de 10 minutes, effet d'1 minute) : Speed I, et chacun de vos coups au corps-à-corps enflamme l'adversaire.",
            "Un clic droit avec votre Plume vous projette 50 blocs dans la direction regardée (rechargement de 10 minutes).",
            "À chaque tombée de la nuit, le rôle d'un joueur aléatoire situé à moins de 50 blocs vous est révélé (rien ne se passe si personne n'est à portée).",
        ],
    },
    {
        command: "imitateur",
        name: "Imitateur",
        team: "NEUTRAL",
        lines: [
            "Comme tout rôle solitaire, votre victoire ne peut être que personnelle.",
            "Force I reste active en continu jusqu'à la moitié de l'épisode 6.",
            "Éliminer votre toute première victime vous fait hériter intégralement de son rôle : ses pouvoirs, ses commandes et ses effets deviennent les vôtres.",
            "Votre condition de victoire ne change pas pour autant : rester l'unique survivant demeure obligatoire.",
            "L'instant où vous imitez un rôle, votre Force I disparaît aussitôt.",
        ],
    },
    {
        command: "joueur_de_flute",
        name: "Joueur de Flûte",
        team: "NEUTRAL",
        lines: [
            "Votre victoire est strictement individuelle.",
            "Porter une Flûte sur vous charme automatiquement les joueurs situés à moins de 20 blocs, à raison de +1% toutes les 4 secondes.",
            "Un coup au corps-à-corps ajoute instantanément 10% de charme à la cible touchée (une seule fois par joueur).",
            "Craftez des Flûtes supplémentaires (8 lingots d'or autour d'un bâton) et transmettez-en une par clic droit sur un joueur visé (portée 5 blocs, une seule par joueur).",
            "Le joueur qui reçoit une Flûte charme à son tour les autres, sans le savoir, deux fois plus lentement que vous, et ne peut plus s'en séparer (il ne l'apprendra qu'au début de l'épisode suivant).",
            "Des bonus cumulatifs se débloquent selon le nombre total de joueurs charmés à 100% (comptés même après leur mort) : 3 → +2 cœurs, 6 → Force 0.5, 9 → Force I + Speed 0.5, 12 → +1 cœur, la totalité des vivants (au moins 6) → Résistance I.",
        ],
    },
];
